const weatherData = [
  {
    title: "Влажность",
    icon: "./icons/humidity.svg",
    value: "75 %",
    progressBar: "./value-icons/humidity-75.svg",
    text1: null,
    text2: null,
    textMin: "0%",
    textMax: "100%",
  },
  {
    title: "Давление",
    icon: "./icons/barometr.svg",
    value: "761",
    progressBar: "./value-icons/barometr-761.svg",
    text1: "Повышенное",
    text2: null,
    textMin: null,
    textMax: null,
  },
  {
    title: "Видимость",
    icon: "./icons/visibility.svg",
    value: "28 км",
    progressBar: "./value-icons/visibility-25.svg",
    text1: "Нормальная",
    text2: null,
    textMin: null,
    textMax: null,
  },
  {
    title: "Рассвет",
    icon: "./icons/sunrise.svg",
    value: "8:42",
    progressBar: null,
    text1: "Прошло: ",
    text2: "02:47",
    textMin: null,
    textMax: null,
  },
  {
    title: "Закат",
    icon: "./icons/sunset.svg",
    value: "16:37",
    progressBar: null,
    text1: "Осталось: ",
    text2: "05:08",
    textMin: null,
    textMax: null,
  },
  {
    title: "Сила ветра",
    icon: "./icons/vane.svg",
    value: "2 м/с",
    progressBar: null,
    text1: "Северо-",
    text2: "западный",
    textMin: null,
    textMax: null,
  },
];
