export const cardsData = [
  {
    title: "Влажность",
    icon: "./icons/humidity.png",
    value: "75 %",
    progressBar: 1,
    gradient: null,
    text1: null,
    text2: null,
    textMin: "0%",
    textMax: "100%",
  },
  {
    title: "Давление",
    icon: "./icons/barometr.png",
    value: "761",
    progressBar: 1,
    gradient: 1,
    text1: "Повышенное",
    text2: null,
    textMin: null,
    textMax: null,
  },
  {
    title: "Видимость",
    icon: "./icons/visibility.png",
    value: "28 км",
    progressBar: 1,
    gradient: null,
    text1: "Нормальная",
    text2: null,
    textMin: null,
    textMax: null,
  },
  {
    title: "Рассвет",
    icon: "./icons/sunrise.png",
    value: "8:42",
    progressBar: null,
    gradient: null,
    text1: "Прошло: ",
    text2: "2:47",
    textMin: null,
    textMax: null,
  },
  {
    title: "Закат",
    icon: "./icons/sunset.png",
    value: "16:37",
    progressBar: null,
    gradient: null,
    text1: "Осталось: ",
    text2: "05:08",
    textMin: null,
    textMax: null,
  },
  {
    title: "Сила ветра",
    icon: "./icons/airplane.png",
    value: "2 м/с",
    progressBar: null,
    gradient: null,
    text1: "Северо-",
    text2: "западный",
    textMin: null,
    textMax: null,
  },
];

export const directionAngles = {
  Северный: 315,
  "Северо-восточный": 0,
  Восточный: 45,
  "Юго-восточный": 90,
  Южный: 135,
  "Юго-западный": 180,
  Западный: 225,
  "Северо-западный": 270,
};

export const carouselDataHour = [
  {
    date: "2024-01-06",
    time: "12:00",
    condition: "broken-clouds",
    temperature_celsius: "-7",
  },
  {
    date: "2024-01-06",
    time: "15:00",
    condition: "broken-clouds",
    temperature_celsius: "-5",
  },
  {
    dateTime: "2024-01-06",
    time: "18:00",
    condition: "broken-clouds",
    temperature_celsius: "-7",
  },
  {
    dateTime: "2024-01-06",
    time: "21:00",
    condition: "broken-clouds",
    temperature_celsius: "-9",
  },
  {
    dateTime: "2024-01-07",
    time: "00:00",
    condition: "broken-clouds",
    temperature_celsius: "-11",
  },
  {
    dateTime: "2024-01-07",
    time: "03:00",
    condition: "broken-clouds",
    temperature_celsius: "0",
  },
];

export const carouselDataDay = [
  {
    date: "2024-01-07",
    condition: "few-clouds",
    day_temperature: "-17",
    night_temperature: "-11",
  },
  {
    date: "2024-01-08",
    condition: "few-clouds",
    day_temperature: "-16",
    night_temperature: "-8",
  },
  {
    date: "2024-01-09",
    condition: "broken-clouds",
    day_temperature: "-8",
    night_temperature: "-2",
  },
  {
    date: "2024-01-10",
    condition: "broken-clouds",
    day_temperature: "-10",
    night_temperature: "-9",
  },
];
